import { describe, it, expect } from 'vitest';
import {
  CAD_AI_SYSTEM_PROMPT,
  ARCHITECT_VARIANT_PREAMBLE, ARCHITECT_PLANNER_PREAMBLE,
  DRAFTER_PREAMBLE,
  DRAFTER_PLACEMENT_CONTRACT,
  CRITIC_PREAMBLE,
  REPAIR_PREAMBLE,
  SHEET_REVIEWER_PREAMBLE,
} from './system-prompt';
import { validateOpenScadCode } from './code-validator';
import { DRAFTER_CLEARANCE_JOINTS_NOTE } from './graph';

const PROMPTS: Record<string, string> = {
  CAD_AI_SYSTEM_PROMPT,
  ARCHITECT_VARIANT_PREAMBLE, ARCHITECT_PLANNER_PREAMBLE,
  DRAFTER_PREAMBLE,
  DRAFTER_PLACEMENT_CONTRACT,
  CRITIC_PREAMBLE,
  REPAIR_PREAMBLE,
  SHEET_REVIEWER_PREAMBLE,
};

/** Every fenced block tagged `openscad`, with the prompt it came from. */
function openscadBlocks(): Array<{ prompt: string; index: number; code: string }> {
  const out: Array<{ prompt: string; index: number; code: string }> = [];
  for (const [prompt, text] of Object.entries(PROMPTS)) {
    const re = /```openscad\n([\s\S]*?)```/g;
    let m: RegExpExecArray | null;
    let index = 0;
    while ((m = re.exec(text)) !== null) {
      out.push({ prompt, index: index++, code: m[1] });
    }
  }
  return out;
}

const words = (s: string) => s.trim().split(/\s+/).length;

/**
 * Ceilings, not targets. The system prompt rides on every model call and each
 * preamble on its node's calls, so a rewrite that quietly doubles one of them
 * costs tokens on every run - this makes that a failing test rather than a
 * slow drift.
 * ARCHITECT_VARIANT_PREAMBLE was 519/520 before the DESIGN APPROACH rule; raised once for it.
 * Raised again when spec coherence and declared holes became enforced checks:
 * removing the fabrication framing paid for them, so the cost that actually
 * matters - system prompt plus preamble, per call - stayed within 3 %.
 */
const WORD_BUDGET: Record<string, number> = {
  CAD_AI_SYSTEM_PROMPT: 1100,
  ARCHITECT_VARIANT_PREAMBLE: 1000,
  ARCHITECT_PLANNER_PREAMBLE: 680,
  DRAFTER_PREAMBLE: 560,
  DRAFTER_PLACEMENT_CONTRACT: 260,
  CRITIC_PREAMBLE: 460,
  REPAIR_PREAMBLE: 500,
  SHEET_REVIEWER_PREAMBLE: 250,
};

/**
 * Fabrication vocabulary that must not return to the prompts.
 *
 * cadai is a parametric modelling tool. Priming the models with 3D-printing
 * process framing made them import constraints nobody asked for - nozzle-driven
 * wall minimums, overhang and support reasoning, material advice - and then
 * alter the requested geometry to satisfy them. Printability belongs to a
 * separate, opt-in node. This test is the guard, because the framing crept in
 * one helpful sentence at a time and would again.
 */
const FABRICATION_TERMS =
  /\b(FDM|nozzle|PLA|PETG|ABS\/ASA|filament|slicer|slicing|layer height|layer adhesion|extrusion width|infill|raft|brim|overhang|unsupported area|bridging|support structures?|build plate|warp)\b/i;

describe('system prompts', () => {
  it('embeds only OpenSCAD examples that compile to real 3D geometry', async () => {
    const blocks = openscadBlocks();
    // A prompt with zero examples would pass vacuously; the idioms are the point.
    // One remains: the format example. Edge idioms were removed and gussets
    // are generated by code, so the prompt no longer teaches them.
    expect(blocks.length).toBeGreaterThanOrEqual(1);

    for (const b of blocks) {
      expect(b.code, `${b.prompt} block ${b.index} uses 3D minkowski`).not.toMatch(/minkowski\s*\(/);
      const res = await validateOpenScadCode(b.code);
      expect(res.valid, `${b.prompt} block ${b.index} failed: ${res.error}\n${b.code}`).toBe(true);
      expect(res.isManifold, `${b.prompt} block ${b.index} is non-manifold`).not.toBe(false);
      // Silent corruption: an undeclared identifier compiles to the wrong solid.
      const silent = res.warnings.filter((w) => w.code === 'unknown_variable' || w.code === 'unknown_module');
      expect(silent, `${b.prompt} block ${b.index} references an undeclared identifier`).toHaveLength(0);
    }
  });

  it('keeps the substrings the graph and its tests depend on', () => {
    expect(DRAFTER_PLACEMENT_CONTRACT).toContain('PLACEMENT CONTRACT');
    // The contract is appended only when the spec has placements; a copy of
    // its heading in another prompt would defeat graph-placement.test.ts.
    for (const [name, text] of Object.entries(PROMPTS)) {
      if (name === 'DRAFTER_PLACEMENT_CONTRACT') continue;
      expect(text, `${name} duplicates the placement contract heading`).not.toContain('PLACEMENT CONTRACT');
      expect(text, `${name} blurs the compile/geometry split`).not.toContain('compilation or geometry error');
    }
  });

  it('teaches every node the spec fields for flat faces and stress points, and no edge treatments', () => {
    for (const field of ['bedFace', 'stressPoints']) {
      expect(CAD_AI_SYSTEM_PROMPT).toContain(field);
      expect(ARCHITECT_VARIANT_PREAMBLE).toContain(field);
    }
    // Edge treatments were removed from generation: no prompt may ask for or
    // teach a chamfer, fillet, round, elephant-foot or lead-in. Sentences that
    // prohibit them ("never", "no", "sharp") are the only place the words may
    // still appear.
    const withoutProhibitions = (text: string) =>
      text.split(/(?<=\.)\s+|\n/).filter((s) => !/\b(never|no|sharp)\b/i.test(s)).join('\n');
    for (const [name, text] of Object.entries(PROMPTS)) {
      expect(withoutProhibitions(text), `${name} still teaches an edge treatment`).not.toMatch(
        /edgeTreatment|elephant|lead-in|lead_in|teardrop|\b(fillets?|chamfers?|rounding)\b/i
      );
    }
    expect(CAD_AI_SYSTEM_PROMPT).toMatch(/Edges stay sharp/);
    // Gussets are declared as numbers by the Architect and built by code.
    expect(ARCHITECT_VARIANT_PREAMBLE).toContain('stressPoints[].gusset');
    expect(DRAFTER_PREAMBLE).toMatch(/never model a gusset/i);
    expect(REPAIR_PREAMBLE).toMatch(/never model or remove one/i);

    // The drafter implements and the repair node must not undo.
    expect(DRAFTER_PREAMBLE).toContain('stressPoints');
    expect(REPAIR_PREAMBLE).toMatch(/never delete/i);
    expect(REPAIR_PREAMBLE).toContain('flat-packable');
    // The critic checks posture but is told not to judge sizes it cannot see.
    expect(CRITIC_PREAMBLE).toContain('bedFace');
    expect(CRITIC_PREAMBLE).toMatch(/empty findings list is the correct/i);
    expect(CAD_AI_SYSTEM_PROMPT).toMatch(/NEVER 3D minkowski/);
    // One pose rule: nobody is told to author in print pose any more.
    for (const [name, text] of Object.entries(PROMPTS)) {
      expect(text, `${name} still talks about PRINT pose authoring`).not.toMatch(/PRINT pose/);
      expect(text, `${name} still offers a print layout`).not.toMatch(/print layout/i);
    }
    for (const field of ['localExtents', 'positionNote']) {
      expect(ARCHITECT_VARIANT_PREAMBLE).toContain(field);
    }
    expect(CAD_AI_SYSTEM_PROMPT).toMatch(/ground plane; nothing is ever below it/);
    expect(ARCHITECT_VARIANT_PREAMBLE).toMatch(/below z = 0/);
    expect(DRAFTER_PREAMBLE).toMatch(/below z = 0/);
    expect(DRAFTER_PREAMBLE).toContain('localExtents');
    expect(DRAFTER_PLACEMENT_CONTRACT).toContain('localExtents');
    expect(REPAIR_PREAMBLE).toContain('floating');
  });

  it('frames the work as parametric modelling, with no fabrication process', () => {
    for (const [name, text] of Object.entries(PROMPTS)) {
      const hit = FABRICATION_TERMS.exec(text);
      expect(hit?.[0], `${name} reintroduces fabrication framing ("${hit?.[0]}")`).toBeUndefined();
    }
    // The two rules that sound fabrication-related are geometric invariants and
    // must survive: they are measured, not advisory.
    expect(CAD_AI_SYSTEM_PROMPT).toMatch(/Edges stay sharp/);
    expect(CAD_AI_SYSTEM_PROMPT).toMatch(/nothing is ever below it/);
    // Scope discipline: the request is the brief, not a starting point.
    expect(ARCHITECT_PLANNER_PREAMBLE).toMatch(/BUILD WHAT WAS ASKED FOR/);
  });

  it('teaches the checks that close the placement blind spots', () => {
    // Spec self-coherence: the only check that can catch the Architect.
    expect(ARCHITECT_VARIANT_PREAMBLE).toMatch(/COHERENCE IS CHECKED/);
    expect(REPAIR_PREAMBLE).toContain('coherence');
    // Rotation semantics, the arithmetic that produced wrong angled joints.
    expect(CAD_AI_SYSTEM_PROMPT).toMatch(/about its OWN min corner/);
    expect(CAD_AI_SYSTEM_PROMPT).toMatch(/180 - a/);
    // Declared holes, probed after the compile.
    for (const text of [CAD_AI_SYSTEM_PROMPT, ARCHITECT_VARIANT_PREAMBLE, DRAFTER_PREAMBLE]) {
      expect(text).toContain('holes');
    }
    expect(REPAIR_PREAMBLE).toContain('feature');
    // Handedness, which no measurement can see.
    expect(DRAFTER_PREAMBLE).toMatch(/mirror\(\)/);
    expect(REPAIR_PREAMBLE).toContain('handedness');
  });

  it('teaches explicit shape semantics, measurement rules, design contract, and drops retired fields', () => {
    // Plane mapping and cylinder diameter rule in vocabulary
    expect(CAD_AI_SYSTEM_PROMPT).toMatch(/xz\s*->\s*\(x,\s*z\),\s*extruded along y/i);
    expect(CAD_AI_SYSTEM_PROMPT).toMatch(/two cross-axis extents are equal and are the diameter/i);

    // ARCHITECT_VARIANT_PREAMBLE contains WHAT WILL BE MEASURED, DESIGN CONTRACT, and gusset fields
    expect(ARCHITECT_VARIANT_PREAMBLE).toContain('WHAT WILL BE MEASURED');
    expect(ARCHITECT_VARIANT_PREAMBLE).toContain('DESIGN CONTRACT');
    expect(ARCHITECT_VARIANT_PREAMBLE).toContain('corner [x, y, z]');
    expect(ARCHITECT_VARIANT_PREAMBLE).toContain("along ('x' | 'y')");
    expect(ARCHITECT_VARIANT_PREAMBLE).toContain("floorDir ('+' | '-')");
    expect(ARCHITECT_VARIANT_PREAMBLE).toContain('legMm');
    expect(ARCHITECT_VARIANT_PREAMBLE).toContain('thicknessMm');
    expect(ARCHITECT_VARIANT_PREAMBLE).toContain('at[]');

    // No prompt mentions retired spec fields
    for (const [name, text] of Object.entries(PROMPTS)) {
      expect(text, `${name} still mentions retired spec fields`).not.toMatch(
        /\b(dimensions|form|useModules|matingFaces)\b/
      );
    }
  });

  it('stays within its word budget', () => {
    for (const [name, text] of Object.entries(PROMPTS)) {
      expect(words(text), `${name} is ${words(text)} words`).toBeLessThanOrEqual(WORD_BUDGET[name]);
    }
  });

  it('Task D: planner preamble requires visible structural difference and literal variant A', () => {
    expect(ARCHITECT_PLANNER_PREAMBLE).toMatch(/VISIBLE STRUCTURE/);
    expect(ARCHITECT_PLANNER_PREAMBLE).toMatch(/Variant A follows the request literally/i);
    expect(ARCHITECT_PLANNER_PREAMBLE).toMatch(/When fewer than 2 visibly different variants make sense, plan only 1/i);
  });

  it('Task D: variant preamble requires guide for held objects and states host/inserted convention', () => {
    expect(ARCHITECT_VARIANT_PREAMBLE).toMatch(/holds or supports an object/i);
    expect(ARCHITECT_VARIANT_PREAMBLE).toMatch(/guides envelope at its resting pose/i);
    expect(ARCHITECT_VARIANT_PREAMBLE).toMatch(/partA is the HOST/i);
    expect(ARCHITECT_VARIANT_PREAMBLE).toMatch(/partB is the INSERTED part/i);
    expect(ARCHITECT_VARIANT_PREAMBLE).toMatch(/do NOT model mating cavities yourself/i);
    expect(CAD_AI_SYSTEM_PROMPT).toMatch(/partA is the host/i);
    expect(CAD_AI_SYSTEM_PROMPT).toMatch(/partB is inserted/i);
    expect(CAD_AI_SYSTEM_PROMPT).toMatch(/cuts the host's cavity/i);
  });

  it('Task D: drafter prompt mentions code-cut cavities', () => {
    expect(DRAFTER_CLEARANCE_JOINTS_NOTE).toContain('Mating cavities for clearance joints are cut by code after your script (host = partA)');
    expect(DRAFTER_CLEARANCE_JOINTS_NOTE).toContain('Do not model slots, sockets or holes for inserted parts');
  });
});
